SEARCH_HEADERS = {
    "X-Restli-Protocol-Version": "2.0.0",
    "X-Li-Pem-Metadata": "Voyager - Search Typeahead Page=global-search-typeahead-result",
    "Accept": "application/vnd.linkedin.normalized+json+2.1",
    "Csrf-Token": "ajax:3890344252407511716",
    "Sec-Ch-Ua-Platform": '"Windows"',
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0",
    "Referer": "https://www.linkedin.com/feed/",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-Dest": "empty",
    "Host": "www.linkedin.com",
    "Accept-Encoding": "gzip, deflate",
    "Sec-Fetch-Mode": "cors",
    "X-Li-Lang": "en_US",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
    "Sec-Ch-Ua-Mobile": "?0",
}